import streamlit as st
from streamlit_extras.add_vertical_space import add_vertical_space


def Stories():
    tab1, tab2,tab3,tab4,tab5,tab6,tab7,tab8,tab9,tab10 = st.tabs(['story 1','story 2', 'story 3','story 4','story 5','story 6','story 7','story 8','story 9','story 10'])
    with tab1:
        st.subheader("story 1")
        st.write("Once upon a time, in the bustling halls of West Windsor-Plainsboro High School South (HSS), a new student named Raj arrived from India. Raj was an innocent and curious individual, eager to adapt to his new environment. Little did he know that his journey in this school would be filled with mystery and intrigue.")
        add_vertical_space()
        st.write("Walking down the hall to his first class, Raj almost bumped into someone.“Watch where you’re going dude!” the person he almost bumped into yells not unkindly.Bustling was definitely the right way to describe this place. Everyone moved about, knowing where to go and how to skillfully avoid accidents. Well, everyone except Raj. Although that probably had something to do with the fact that he was new.")
        add_vertical_space()
        st.write("Luckily, was starting to get the hang of the schedule. As Raj settled into his classes, he noticed two distinct personalities among his classmates. The first of these was Ram Panchangam, a highly intelligent and puzzle-loving student, who always seemed to be one step ahead in solving mysteries.")
        add_vertical_space()
        st.write("Raj had met Ram on his first day in his forensics class. Raj and Ram were assigned to sit next to each other. Raj shyly smiled at Ram, not sure how to approach a new person.")
        add_vertical_space()
        st.write("“Hey, I’ve never seen you around before. I’m Ram, what’s your name? Why did you take this class? I want to be a detective so that’s why I’m here, you know cause it would totally help me I’m sure!”")
        add_vertical_space()
        st.write("Well, it seemed as though Ram was the opposite, greeting Raj excitedly as though he wasn’t a complete stranger.")
        add_vertical_space()
        st.write("“Uh, I’m Raj. I just took it because I thought it would be cool. And um, good for you, the uh, detective stuff.” Raj responded, voice wavering a bit.")
        add_vertical_space()
        st.write("“It’s great to meet you Raj! I guess we’ll be partners for this marking period!” Ram responded enthusiastically.")
        add_vertical_space()
        st.write("Throughout the next few weeks, Raj and Ram got to learn about each other, like their strengths and weaknesses. Raj got more comfortable with Ram and opened up, earning each other as friends.")
        add_vertical_space()
        st.write("On the other hand, Raj met Trishna Shyamala, who had a malicious nature and took pleasure in causing problems for others, including Raj.")
        add_vertical_space()
        st.write("Raj had met Trishna on his second day, during gym class. Raj had always had good intuition so he knew something was off with Trishna. After his meeting with Ram, Raj’s confidence had improved a bit. So, he felt confident enough to introduce himself to the boy with a gym locker next to his before class started.")
        add_vertical_space()
        st.write("“Hi, I’m Raj. I’m new here,” Raj said, extending his hand.")
        add_vertical_space()
        st.write("“And I don’t care, newbie,” Trishna replied arrogantly, walking away, leaving a stunned Raj behind.")
        add_vertical_space()
        st.write("After that, Raj decided it might be best to stay away from Trishna. Unfortunately, that simply didn’t seem to be an option for him…")
        add_vertical_space()
        st.write("One day, Raj stumbled upon a peculiar painting in the school hallway. The painting depicted a compass pointing southeast, captivating his attention. Below the compass, a riddle was inscribed:")
        add_vertical_space()
        st.write('.. -. / ... -.-. .... --- --- .-.. --..-- / .- / .--. .- .. -. - .. -. --. / .-- .. - .... / -.-. --- -- .--. .- ... ... / -... --- .-.. -.. --..-- / .--. --- .. -. - ... / ... --- ..- - .... . .- ... - --..-- / .- / - .- .-.. . / - --- / ..- -. ..-. --- .-.. -.. .-.-.- / .-.. --- --- -.- / -... . .-.. --- .-- --..-- / .-- .... . .-. . / .--. .. .-. .- - . ... / .-. --- .- -- --..-- / .... --- .-- / -- .- -. -.-- / --. --- --- -.. / . -.-- . ... / -.-. .- .-.. .-.. / .. - / .... --- -- . ..--..')
        add_vertical_space()
        st.write(".- / .--. .. .-. .- - . / .- .-- .- .. - ... --..-- / .- / -.. .- .-. .. -. --. / ... .. --. .... - --..-- / -... ..- - / .... --- .-- / -- .- -. -.-- / . -.-- . ... / ... .... .. -. . / .-- .. - .... / .-.. .. --. .... - ..--.. ... . . -.- / - .... . / .- -. ... .-- . .-. --..-- / .-.. . - / -.-. ..- .-. .. --- ... .. - -.-- / --. ..- .. -.. . --..-- / - .... . / .--. .- .. -. - .. -. --. .----. ... / ... . -.-. .-. . - / .. - / ... .... .- .-.. .-.. / -.-. --- -. ..-. .. -.. . .-.-.-")
        h = st.text_input("what is the answer to this riddle?")
        if h == '1':
            st.success("Riddle sloved")
            st.balloons()
            st.write("Intrigued by the riddle, Raj immediately sensed that solving it would lead him closer to the heart of the mystery surrounding the school. With determination in his eyes, he sought the help of Ram Panchangam, who had a reputation for being skilled at puzzles.")
            add_vertical_space()
            st.write("“Hey Ram, I have to ask you something,” Raj said, sitting down at their lunch table.")
            add_vertical_space()
            st.write("“Of course Raj, what’s up dude?” Ram said, once they finished chewing their food.")
            add_vertical_space()
            st.write("“So you know how you’re good at solving puzzles and you want to be a detective and all,” Raj continues once Ram nods. “There’s this painting in the hallway with a compass on it. There’s what looks like a riddle underneath. I was wondering if you would help me solve it?”")
            add_vertical_space()
            st.write("“Sure dude, I would love to! Let’s eat and then I’ll see if I can work my magic,” Ram replied eagerly. “But dude, I have to warn you about Trishna.”")
            add_vertical_space()
            st.write("“Who’s that?”")
            add_vertical_space()
            st.write("“He’s right there actually,” Ram whispers, pointing. Following their finger, Raj realizes that Trishna was also the guy who was rude to him in gym class.")
            add_vertical_space()
            st.write("“Oh I know him. He was quite rude.”")
            add_vertical_space()
            st.write("“He has a habit of going out of his way to cause problems for everyone.” Ram warned.")
            add_vertical_space()
            st.write("Ram then joined Raj in deciphering the riddle. They examined the painting closely, noting the details of the compass pointing southeast. Ram's sharp mind quickly realized that 'below' referred to a lower part of the school building, where the art classes were held. They followed the clue and arrived at the art room.")
            add_vertical_space()
            st.write("Inside the art room, they discovered a large mural of a pirate ship sailing through stormy seas. Amongst the chaos, they noticed several pairs of glowing eyes amidst the darkness. Raj and Ram counted the eyes, carefully examining each part of the mural. After a meticulous count, they arrived at the answer: seven pairs of eyes.")
            add_vertical_space()
            st.write("“Ram, we figured it out!” Raj exclaimed.")
            add_vertical_space()
            st.write("“Firstly, we’re not done, and secondly, keep it down! You don’t want Trishna to show up!” Ram shushed.")
            add_vertical_space()
            st.write("“Oh sorry dude.” Raj responded, looking around. “I guess we just work in secret to find out what the hidden message is.”")
            add_vertical_space()
            st.write("Ram nodded and the duo revisited the original riddle, pondering its meaning.")
            add_vertical_space()
            st.write("“Wait, I think the ‘glowing eyes’ might just be stars. This kind of looks like a constellation,” Raj said, eyes growing wide.")
            add_vertical_space()
            st.write("“Oh you might be right! That kind of looks like Orion, the hunter,  now that you mention it,” Ram added. They had figured out the next important piece of the puzzle.")
            add_vertical_space()
            st.write("Excitement coursing through their veins, Raj and Ram searched for clues related to Orion. They soon discovered a hidden compartment behind the mural, which contained a map leading to a buried treasure within the school grounds.")
            add_vertical_space()
            st.write("Together, they embarked on a thrilling adventure, following the clues on the map. They solved puzzles, navigated through secret passages, and overcame challenges along the way. With each step, their bond grew stronger, and they became an unstoppable duo. Try as he might, Trishna failed to trip them up no matter how.")
            add_vertical_space()
            st.write("Finally, they reached the designated spot on the map, where they unearthed a chest filled with ancient artifacts and treasures.")
            add_vertical_space()
            st.write("“Ram, now we got it for sure!” Raj exclaimed, practically vibrating where he stood.")
            add_vertical_space()
            st.write("“Yea I think we do,” Ram replied calmly for once. Oh how the turntables in their attitudes.")
            add_vertical_space()
            st.write("Their discovery not only solved the mystery surrounding the painting but also revealed the rich history of the school.")
            add_vertical_space()
            st.write("Raj and Ram were hailed as heroes, celebrated for their wit and perseverance. Trishna Shyamala, realizing his attempts to sabotage their efforts had failed, slinked away in defeat.")
            add_vertical_space()
            st.write("As Raj and Ram returned to their everyday lives at HSS, they cherished the memories they had forged together and continued to solve mysteries that came their way. For example, one time someone asked them to find their lost necklace.")
            add_vertical_space()
            st.write("“Ram, Raj, I lost my necklace, will you please help me find it?” someone asked.")
            add_vertical_space()
            st.write("“We’ll do it,” Ram replied, once both Ram and Raj had nodded at each other.")
            add_vertical_space()
            st.write("They had found out someone had stolen it and made sure to return the necklace to the rightful owner. Their remarkable journey had not only unveiled the secrets of the school but also solidified a friendship that would last a lifetime.")
            add_vertical_space()
            st.write("Word of their adventure quickly spread throughout West Windsor-Plainsboro High School South, capturing the imagination of their fellow students. Inspired by Raj and Ram's bravery and intellect, many students formed their own detective clubs and began unraveling their own mysteries within the school.")
            add_vertical_space()
            st.write("Raj and Ram gladly shared their expertise, offering guidance and mentoring to the newfound detectives. They became a source of inspiration, encouraging their peers to embrace their curiosity and think outside the box. The school's atmosphere transformed into a hub of excitement and exploration, with students eagerly searching for hidden secrets and puzzles.")
            add_vertical_space()
            st.write("As time went on, Raj and Ram became known as the dynamic duo of HSS. Their reputation grew not only within the school but also in the wider community. Local newspapers featured articles about their adventures, and they were even invited to give talks and workshops on problem-solving and critical thinking.")
            add_vertical_space()
            st.write("The school administration recognized the positive impact Raj and Ram had on the student body and decided to create an annual 'Mystery Week' event. ")
            add_vertical_space()
            st.write("“Attention students, next week is our first annual ‘Mystery Week’ event. During this week, the entire school will be transformed into an interactive puzzle-filled playground. Clues will be hidden in lockers, classrooms, and even in the cafeteria, challenging students to solve intricate riddles and codes. All students are encouraged to participate.” a voice spoke over the intercom. “Ram Panchangam and Raj Talvaar, please come to the office.”")
            add_vertical_space()
            st.write("“As our dynamic duo, we want both of you to design the grand mystery at the end of ‘Mystery Week’. Would you both be interested in doing so?” a member of the administration asked, once both Ram and Raj were seated.")
            add_vertical_space()
            st.write("The two looked at each other as though they had a silent conversation without needing to speak. Looking back over, Raj started, “We would love to!”")
            add_vertical_space()
            st.write("“It would be so cool for us to do that,” Ram added, eyes shining at the prospect of being put in charge of something like this.")
            add_vertical_space()
            st.write("“We’re glad you both agreed. Brainstorm tonight, and let’s meet during your lunch tomorrow”")
            add_vertical_space()
            st.write("Raj and Ram were given the honor of designing the grand finale mystery, a tradition that would continue year after year. The school community eagerly awaited Mystery Week, knowing that it would be an exhilarating and mind-bending experience.")
            add_vertical_space()
            st.write("Beyond their adventures, Raj and Ram excelled academically. They continued to impress their teachers with their sharp intellect and problem-solving skills.")
            add_vertical_space()
            st.write("Years later, as they prepared to graduate from high school, Raj and Ram reflected on their incredible journey. Raj discovered a passion for physics, while Ram's interest in puzzles led him to pursue a career in game design. They realized that their time at HSS had not only shaped their own lives but had also impacted the lives of their classmates. The spirit of curiosity and exploration they had ignited continued to thrive within the school, fostering a community of lifelong learners.")
            add_vertical_space()
            st.write("As they bid farewell to West Windsor-Plainsboro High School South, Raj and Ram knew that their friendship and shared love for mysteries would endure. They were excited to embark on new adventures and solve even greater puzzles, knowing that they could overcome any challenge with their bond and unwavering determination.")
            add_vertical_space()
            